version: "2"

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${APP_NAME}/app:latest
    ports:
      - "${APP_LOCAL_PORT}:80"
    volumes:
      - "./project:/var/www/html"
    working_dir: /var/www/html
    networks:
      - "appnet"
    links:
      - "db:${APP_NAME}-local"
    depends_on:
      - db

  db:
    container_name: ${APP_NAME}-database
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_LOCAL_PORT}:3306"
    networks:
      - "appnet"
    volumes:
      - "dbdata:/var/lib/mysql"

  phpmyadmin:
    container_name: ${APP_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${PMA_LOCAL_PORT}:80"
    networks:
      - "appnet"
    depends_on:
      - db

  node:
    container_name: ${APP_NAME}-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: ${APP_NAME}/node:latest
    user: node
    networks:
      - "appnet"
    volumes:
      - "./project:/opt"
    working_dir: /opt

networks:
  appnet:
    driver: bridge

volumes:
  dbdata:
    driver: local
